# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- none
jobs:
- job: Build_JS
  displayName: "Build JS Bundle"
  pool:
    vmImage: 'macos-latest'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'
  - script: |
      npm install
    displayName: 'npm install'
  # - task: ArchiveFiles@2
  #   displayName: 'Archive Source'
  #   inputs:
  #     rootFolderOrFile: '$(Build.SourcesDirectory)'
  #     archiveFile: '$(Build.ArtifactStagingDirectory)/dest.zip'
  # - task: PublishPipelineArtifact@1
  #   displayName: 'Publish Source'
  #   timeoutInMinutes: 1
  #   inputs:
  #     targetPath: '$(Build.ArtifactStagingDirectory)/'
  #     artifact: 'dist'
  #     publishLocation: 'pipeline'
      
- job: build_ios
  variables:
    - group: mobile-app

  displayName: "Build iOS IPA"
  dependsOn: Build_JS
  condition: succeeded('Build_JS')
  pool:
    vmImage: macos-latest
  
  steps:
  # - task: DownloadPipelineArtifact@2
  #   displayName: 'Download build artifact'
  #   inputs:
  #     buildType: 'current'
  #     artifactName: 'dist'
  #     targetPath: '$(Build.ArtifactStagingDirectory)'
  
  # - task: ExtractFiles@1
  #   inputs:
  #     archiveFilePatterns: '$(Build.ArtifactStagingDirectory)/**/*.zip'
  #     destinationFolder: '$(Build.ArtifactStagingDirectory)/'
  #     cleanDestinationFolder: false

  - script: |
      npm install -g @ionic/cli@6.18.1
    displayName: 'Install Ionic'
  
  - script: |
      npm install -g cordova@11.0.0
    displayName: 'Install Cordova'
  
  # - task: CmdLine@2
  #   inputs:
  #     script: 'cd $(Build.ArtifactStagingDirectory)/s'
  #   displayName: 'Change Directory'
  
  - task: CmdLine@2
    inputs:
      script: 'ionic cordova platform add ios@6.2.0 --save'
    displayName: 'add ios platform'
  
  - task: InstallAppleCertificate@2
    inputs:
      certSecureFile: 'distribute.p12'
      certPwd: '$(p12password)'
      keychain: 'temp'
    
  - task: InstallAppleProvisioningProfile@1
    inputs:
      provisioningProfileLocation: secureFiles
      provProfileSecureFile: 'toonworldapp.mobileprovision'

  # - task: CmdLine@2
  #   inputs:
  #     script: 'ionic cordova build ios --prod'
  #   displayName: 'Build iOS'
  
  - task: Xcode@5
    inputs:
      actions: 'build'
      xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
      packageApp: true
      signingOption: 'manual'
      signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
      provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'
  
  - task: CopyFiles@2
    inputs:
      contents: '**/*.ipa'
      targetFolder: '$(build.artifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
  
  
